apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  # volumes:
    # - name: "webservice-data"
    #   hostPath:
    #     path: "/Users/grey/dev/mnt/web-api"            
    # - name: "nas-data" 
    #   nfs:
    #     server: 192.168.1.4 
    #     path: "/volume1/dev/webservice"
  containers:
    - image: docker.io/nginx:1.18
      name: nginx
      # volumeMounts:
      #   - mountPath: "/mnt/web-api"
      #     name: "nas-data"
