apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  volumes:
    - name: "prometheus-data"
      hostPath:
        path: "/Users/grey/dev/mnt/prometheus"            
    # - name: "nas-data" 
    #   nfs:
    #     server: 192.168.1.4 
    #     path: "/volume1/dev/prometheus"
  containers:
    - image: docker.io/hanmel/prometheus:0.0.1
      name: prometheus
      volumeMounts:
        - mountPath: "/prometheus"
          name: "prometheus-data"
      ports: 
        - containerPort: 9090
          name: http
          protocol: TCP 