apiVersion: v1
kind: Pod
metadata:
  name: webservice
spec:
  containers:
    - image: docker.io/hanmel/webservice:latest
      name: webservice
      ports: 
        - containerPort: 3000
          name: http
          protocol: TCP 

