apiVersion: v1
kind: Pod
metadata:
  name: webservice
  labels:
    app: webservice
spec:
  volumes:
    # - name: "webservice-data"
    #   hostPath:
    #     path: "/Users/grey/dev/mnt/web-api"            
    - name: "nas-data" 
      nfs:
        server: 192.168.1.4 
        path: "/volume1/dev/webservice"
  containers:
    - image: docker.io/hanmel/webservice:0.1.5
      name: webservice
      volumeMounts:
        - mountPath: "/mnt/web-api"
          name: "nas-data"
      ports: 
        - containerPort: 3000
          name: http
          protocol: TCP 

