version: "3.8"
volumes: 
  web-api-volume:
  prometheus-volume:
  grafana-volume:    
services:
  webservice:
    image: webservice
    ports: 
      - 3000:3000
    volumes:
      - type: volume
        source: web-api-volume
        target: /mnt/web-api
  prometheus:
    image: prometheus
    ports:
        - 9090:9090
    volumes:
      - type: volume
        source: prometheus-volume
        target: /prometheus
  grafana:
    image: grafana/grafana
    ports:
        - 3001:3000
    volumes:
        - type: volume
          source: grafana-volume
          target: /var/lib/grafana