apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
  labels:
    app: webservice
spec:
  selector:
    matchLabels:
      app: webservice
  replicas: 1
  template:
    metadata:
      labels:
        app: webservice
    spec:
      volumes:
      # - name: webservicecontent
      #   persistentVolumeClaim:
      #     claimName: pvc-nfs-data
      - name: "nas-data" 
        nfs:
          server: 192.168.1.4 
          path: "/volume1/dev/webservice"
      containers:
      - name: webservice
        image: docker.io/hanmel/webservice:0.1.5
        ports: 
        - containerPort: 3000
          name: http
          protocol: TCP
        volumeMounts:
        # - name: webservicecontent
        #   mountPath: "/mnt/web-api"
        - name: "nas-data" 
          mountPath: "/mnt/web-api"
